name: Build and publish jekyll site

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Jekyll Build and Publish
        uses:  helaili/jekyll-action@master
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
